import enum
from datetime import date, datetime
from typing import Optional
from uuid import UUID

from sqlalchemy import Date, DateTime, Enum, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.mixins import TimestampMixin, UUIDPKMixin


class TaskType(str, enum.Enum):
    IRRIGATION = "irrigation"
    FERTILIZATION = "fertilization"
    INSPECTION = "inspection"
    SOIL = "soil"
    HARVEST = "harvest"
    CUSTOM = "custom"


class TaskStatus(str, enum.Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    SKIPPED = "skipped"


class TaskPriority(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class CropTask(Base, UUIDPKMixin, TimestampMixin):
    __tablename__ = "crop_tasks"

    crop_cycle_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("crop_cycles.id", ondelete="CASCADE"), index=True
    )

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    task_type: Mapped[TaskType] = mapped_column(Enum(TaskType, name="task_type_enum"), nullable=False)
    scheduled_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    status: Mapped[TaskStatus] = mapped_column(Enum(TaskStatus, name="task_status_enum"), default=TaskStatus.PENDING)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    priority: Mapped[TaskPriority] = mapped_column(
        Enum(TaskPriority, name="task_priority_enum"), default=TaskPriority.MEDIUM
    )
    # True for tasks auto-generated by the lifecycle engine, so the UI
    # can visually distinguish "suggested" from "farmer-created" tasks.
    auto_generated: Mapped[bool] = mapped_column(default=False, server_default="false")

    crop_cycle: Mapped["CropCycle"] = relationship(back_populates="tasks")
